language: node_js
node_js:
  - 20
cache:
  directories:
  - node_modules
script:
  - npm run build
dist: jammy
deploy:
  provider: pages
  local_dir: build
  github_token: $github_token
  on:
    branch: master
